### PR TITLE
[ WIP ] Profile base

### PR DESCRIPTION
**Pull request by piyushc0**
New Endpoint(Profile). It is a base for profile

### CODE REVIEW

**Comment by whopiyush** [comment]
Nice Travis Failed,
Ill fix that and merge

**Comment by whopiyush** [comment]
Also, Can I See an example how it looks like?

**Comment by piyushc0** [comment]
why travis keep failing everything. I haven't tested as i can't because of the invalid url.
image

**Comment by ionadev** [comment]
# Asked For Rejection

* image

**Comment by whopiyush** [comment]
# Asked For Rejection

 image

**Pull request closed without merging**
